# any of these constants can be changed, if it makes sense for the program

WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

DEFAULT_IMAGE_SIZE = (100, 100)
DEFAULT_SIDE_BUTTON_IMAGE_SIZE = (200, 100)
DEFAULT_BACK_TO_MENU_COORDINATES = (
WINDOW_WIDTH - DEFAULT_SIDE_BUTTON_IMAGE_SIZE[0], 0)
